# Generated by Django 5.1.1 on 2024-11-06 18:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write a body for your site'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write an introduction for the site', max_length=255),
        ),
    ]
